<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bbcode</string>
		<string>bb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\[[^/][^\]]+\]</string>
	<key>foldingStopMarker</key>
	<string>\[/[^/\]]+\]</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BBCode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\[code=ruby\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.ruby.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.ruby.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=html\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.html.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>text.html.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=rhtml\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.rhtml.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>text.rhtml.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=(js|javascript)\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.js.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.js.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=(css|stylesheet)\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.css.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.css.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=php\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.php.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.php.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=python\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.python.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.python.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=perl\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.perl.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.perl.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=sql\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.sql.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.sql.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=java\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.java.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.java.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=c\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.c.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.c.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[code=yaml\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.code.yaml.bbcode</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\[/code\]</string>
			<key>name</key>
			<string>source.yaml.embedded.bbcode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[[B|b]\])(.*?)(\[/[B|b]\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[[I|i]\])(.*?)(\[/[I|i]\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[url=?(.*?)\])(.*?)(\[/url\])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.tag.value.bbcode</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\[/?[^\]=]*\]</string>
			<key>name</key>
			<string>meta.tag.any.bbcode</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[.*?=(.*?)\]</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.tag.any.bbcode</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.value.bbcode</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.bbcode</string>
	<key>uuid</key>
	<string>F36798B2-6454-4CA3-9560-2DCC3169CE99</string>
</dict>
</plist>
